PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ulo: <http://mathhub.info/ulo#>

SELECT DISTINCT ?direction ?predicate ?other ?otherType ?graph
WHERE {
  VALUES ?focus { <latin:/?UniversalQuantification#> }

  GRAPH ?graph {
    {
      ?focus ?predicate ?other .
      BIND("out" AS ?direction)
    }
    UNION
    {
      ?other ?predicate ?focus .
      BIND("in" AS ?direction)
    }

    OPTIONAL {
      ?other rdf:type ?otherType .
    }
  }
}
ORDER BY ?direction ?predicate ?other ?otherType
